# Development overrides for local testing
baseurl: ""
url: "http://localhost:4000"

# Enable livereload and incremental building for development
livereload: true
incremental: true

# Show future posts and drafts in development
future: true
show_drafts: true

# More verbose output for debugging
verbose: true
