# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: El futuro del ayer, hoy
email: comite.editorial@elfuturodelayerhoy.com
description: >- # this means to ignore newlines until "baseurl:"
  Revista digital abierta a todo tipo de textos, publicamos cada seis meses un
  numero disponible en Amazon de manera digital y fisica. Derechos de autor
  bajo la licencia Attribution 4.0 International.
baseurl: "futuroayerhoy" # the subpath of your site, e.g. /blog
url: "https://vicosurge.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: vicosurge

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections for organizing literary content
collections:
  cuentos:
    output: true
    permalink: /:collection/:name/
  poesia:
    output: true 
    permalink: /:collection/:name/
  ensayos:
    output: true
    permalink: /:collection/:name/
  resenas:
    output: true
    permalink: /:collection/:name/

# Default settings for collections
defaults:
  - scope:
      path: ""
      type: "cuentos"
    values:
      layout: "post"
      category: "cuentos"
  - scope:
      path: ""
      type: "poesia"
    values:
      layout: "post"
      category: "poesia"
  - scope:
      path: ""
      type: "ensayos"
    values:
      layout: "post"
      category: "ensayos"
  - scope:
      path: ""
      type: "resenas"
    values:
      layout: "post"
      category: "resenas"

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

markdown: kramdown

# Custom variables
literary_sections:
  cuentos:
    title: "Cuentos"
    description: "Narrativas breves que exploran la condición humana y mundos imaginarios"
    icon: "📖"
  poesia:
    title: "Poesía" 
    description: "Versos que capturan emociones, imágenes y reflexiones líricas"
    icon: "✨"
  ensayos:
    title: "Ensayos"
    description: "Reflexiones profundas sobre literatura, cultura y sociedad"
    icon: "💭"
  resenas:
    title: "Reseñas"
    description: "Análisis críticos de obras literarias contemporáneas"
    icon: "📝"
